#cloud-config
write_files:
- path: /etc/environment
  content: |
    FOO="BAR"
  append: true
- path: /etc/environment
package_upgrade: true
yum_repos:
  tailscale-stable:
    name: Tailscale stable
    baseurl: https://pkgs.tailscale.com/stable/amazon-linux/2/$basearch
    enabled: 1
    type: rpm
    repo_gpgcheck: 1
    gpgcheck: 0
    gpgkey: https://pkgs.tailscale.com/stable/amazon-linux/2/repo.gpg
packages:
  - yum-utils
  - tailscale
runcmd:
  - "echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.conf"
  - "sudo sysctl -p /etc/sysctl.conf"
  - "sudo systemctl enable --now tailscaled"
  - "sudo systemctl start tailscaled"
  - "sleep 5"
  - "tailscale up -authkey ${auth_key} -hostname tailscale-relay -accept-routes=false --advertise-routes=${vpn_routes}"


